version: '3.9'

services:
  db:
    container_name: book-shelf-db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=pass_db199^
      - POSTGRES_USER=book_user
      - POSTGRES_DB=book_db
    ports:
      - "5432:5432"
    networks:
      - book-shelf-net  
    volumes: 
      - book-shelf-db-data:/var/lib/postgres/data
    restart: always

  book-shelf-app:
    container_name: app
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - book-shelf-net
    ports: 
      - "80:80"   
    restart: always

volumes:
  book-shelf-db-data:
    driver: local

networks:
  book-shelf-net:
    driver: bridge