version: '3.9'

services:
    db:
        container_name: book-shelf-db
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=pass1_
            - POSTGRES_USER=book_user
            - POSTGRES_DB=book_db
        ports:
            - "5432:5432"
        networks:
            - book-shelf-net
        volumes:
            - book-shelf-db-data:/var/lib/postgresql/data
    
    book-shelf-app:
        container_name: book-shelf-app
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - book-shelf-net
        ports:
            - "80:80"

volumes:
    book-shelf-db-data:
        driver: local

networks:
    book-shelf-net:
        driver: bridge